language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t allguitars/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true allguitars/react-test yarn test

after_success:
  - docker build -t allguitars/multi-client ./client
  - docker build -t allguitars/multi-nginx ./nginx
  - docker build -t allguitars/multi-server ./server
  - docker build -t allguitars/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push allguitars/multi-client
  - docker push allguitars/multi-nginx
  - docker push allguitars/multi-server
  - docker push allguitars/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-871255055834
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY